---
name: Build from Dockerfile and push to Snowflake

on:
  workflow_dispatch: # Run manually only

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Snowflake image registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:non-nix"
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/ttydcontainer:latest
